image: maxking/mailman-ci-runner

django16:
  script:
  - tox -e py27-django16

django17:
  script:
  - tox -e py27-django17

django18:
  script:
  - tox -e py27-django18

django19:
  script:
  - tox -e py27-django19
