django16:
  script:
  - tox -e py27-django16
  tags:
  - sqlite

django17:
  script:
  - tox -e py27-django17
  tags:
  - sqlite

django18:
  script:
  - tox -e py27-django18
  tags:
  - sqlite

django19:
  script:
  - tox -e py27-django19
  tags:
  - sqlite
