image: maxking/mailman-ci-runner

django-1.8:
  script:
  - tox -e py27-django18-coverage

django-1.9:
  script:
  - tox -e py27-django19-coverage

django-1.10:
  script:
  - tox -e py27-django110-coverage

pep8:
  script:
  - tox -e pep8

django-latest:
  script:
  - tox -e py27-django-latest
  allow_failure: true
