image: maxking/mailman-ci-runner

django18:
  script:
  - tox -e py27-django18

django19:
  script:
  - tox -e py27-django19

pep8:
  script:
  - tox -e pep8

django-latest:
  script:
  - tox -e py27-django-latest
  allow_failure: true
