---
image: ghcr.io/maxking/mailman-ci-runner

py36-django22:
  stage: test
  script:
    - tox -e py36-django22

py36-django31:
  stage: test
  script:
    - tox -e py36-django31

py36-django32:
  stage: test
  script:
    - tox -e py36-django32

py37-django22:
  stage: test
  script:
    - tox -e py37-django22

py37-django31:
  stage: test
  script:
    - tox -e py37-django31

py37-django32:
  stage: test
  script:
    - tox -e py37-django32

py38-django22:
  stage: test
  script:
    - tox -e py38-django22

py38-django31:
  stage: test
  script:
    - tox -e py38-django31

py38-django32:
  stage: test
  script:
    - tox -e py38-django32

py39-django22:
  stage: test
  script:
    - tox -e py39-django22

py39-django30:
  stage: test
  script:
    - tox -e py39-django30

py39-django31:
  stage: test
  script:
    - tox -e py39-django31

py39-django32:
  stage: test
  script:
    - tox -e py39-django32

py39-django-latest:
  stage: test
  allow_failure: true
  script:
    - printf "Remove all django version restriction from setup.py.\n"
    - sed -E 's/django[<=>,.[:digit:]]+/django/' -i setup.py
    - tox -e py39-django-latest

coverage:
  stage: test
  script:
    - tox -e cov
  artifacts:
    paths:
      - coverage
    expire_in: 5 days

qa:
  stage: test
  script:
    - tox -e qa

upstream-client:
  stage: test
  script:
    - tox -e upstream-client
  only:
    variables:
      - $MAILMANCLIENT_COMMIT_SHA

upstream-django-mailman3:
  stage: test
  script:
    - tox -e upstream-django-mailman3
  only:
    variables:
      - $DJANGO_MAILMAN3_COMMIT_SHA

include:
  - template: SAST.gitlab-ci.yml

variables:
  SAST_DEFAULT_ANALYZERS: "bandit,secrets"
