image: maxking/mailman-ci-runner

django-1.8:
  stage: test
  script:
  - tox -e py27-django18

django-1.10:
  stage: test
  script:
  - tox -e py27-django110

django-1.11:
  stage: test
  script:
  - tox -e py27-django111

coverage:
  stage: test
  script:
  - tox -e coverage
  artifacts:
    paths:
    - coverage
    expire_in: 5 days

pep8:
  stage: test
  script:
  - tox -e pep8

django-1.11-git:
  stage: test
  script:
  - tox -e py27-django111-head
  allow_failure: true

django-latest:
  stage: test
  script:
  - tox -e py27-django-latest
  allow_failure: true

pages:
  stage: deploy
  dependencies:
  - coverage
  script:
  - mv coverage/ public/
  artifacts:
    paths:
    - public
    expire_in: 5 days
  only:
  - master
