image: ghcr.io/maxking/mailman-ci-runner

Python3.7 Django-2.0:
  stage: test
  script:
    - tox -e py36-django20

Python 3.8 Django-2.1:
  stage: test
  script:
    - tox -e py37-django21

Python 3.8 Django-2.2:
  stage: test
  script:
    - tox -e py38-django22

Django-3.0:
  stage: test
  script:
    - tox -e py39-django30

Django-31:
  stage: test
  script:
    - tox -e py39-django31

coverage:
  stage: test
  script:
  - tox -e coverage
  artifacts:
    paths:
    - coverage
    expire_in: 5 days

pep8:
  stage: test
  script:
  - tox -e pep8

django-latest:
  stage: test
  allow_failure: true
  script:
    - tox -e py38-django-latest

upstream-client:
  stage: test
  script:
    - tox -e upstream-client
  only:
    variables:
      - $MAILMANCLIENT_COMMIT_SHA

upstream-django-mailman3:
  stage: test
  script:
    - tox -e upstream-django-mailman3
  only:
    variables:
      - $DJANGO_MAILMAN3_COMMIT_SHA

include:
  - template: SAST.gitlab-ci.yml

variables:
  SAST_DEFAULT_ANALYZERS: "bandit,secrets"
